name: Deploy to server

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Deploy on server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Execute remote ssh commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.INPUT_HOST }}
        username: ${{ secrets.INPUT_USERNAME }}
        key: ${{ secrets.INPUT_KEY }}
        script: |
          cd messenger-backend/
          sh ./deploy.sh